// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Album } from "./Album";
import type { Performer } from "./Performer";
import type { Track } from "./Track";

export type PlayableResult = { "type": "Track", "data": Track } | { "type": "Album", "data": Album } | { "type": "Performer", "data": Performer };
