// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortAlbums } from "./SortAlbums";
import type { SortPerformers } from "./SortPerformers";
import type { SortPlaylists } from "./SortPlaylists";
import type { SortTracks } from "./SortTracks";

export type SortBy = { "SortTracks": SortTracks } | { "SortAlbums": SortAlbums } | { "SortPerformers": SortPerformers } | { "SortPlaylists": SortPlaylists };
