// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Theme = { path_to_background_image: string | null, background_color: string, use_background_image: boolean, font_size1: number, font_size2: number, font_size3: number, font_size4: number, };
