// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Track = { uuid: string, path: string, source_path: string, title: string, album: string, performer: string, };
