// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type UserSettings = { library_paths: Array<string>, themes: Array<Theme>, active_theme: Theme, path_removed: boolean, };
