// <auto-generated />
using System;
using Avalonix.Services.DatabaseService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avalonix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123071316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Avalonix.Model.Media.Playlist.PlaylistData", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastListen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ObserveDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservingDirectory")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
