// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Album = { uuid: string, tracks_ids: Array<string>, title: string, performer: string, cover_uri: string, };
