// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

export type AlbumsContainer = { albums: { [key in string]: Array<Track> }, };
