// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

export type Album = { id: string, tracks: Array<Track>, metadata: AlbumMetadata | null, };

export type AlbumMetadata = { cover: string | null, name: string, artist: string, };
