// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { title: string | null, artist: string | null, album: string | null, genre: string | null, year: number | null, lyrics: string | null, bitrate: number | null, duration_secs: bigint, track_cover_uri: string | null, };
