// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Track } from "./Track";

export type PlayQueue = { tracks: Array<Track>, current_track_index: number, };
