// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackMetadata = { id: Array<number>, file_path: string, title: string, album: string, artist: string, genre: string, bitrate: number, };
